### 1차원 배열 
1. Array를 사용하면 적은 메모리로 많은 데이터를 빠르게 처리 가능 
2. Array 제약 조건 
    - 모든 원소가 같은 자료형 
    - 원소의 개수를 바꿀 수 없음 
    

In [1]:
import numpy as np

In [2]:
ar = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# list를 사용하면 문제점 
d = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
a = []
for i in d:
    a.append(2 * i)
print(a)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


In [5]:
print(2 * ar)
# array를 사용하면 for문을 사용해서 연산해야하는 번거로움을 제거 

[ 0  2  4  6  8 10 12 14 16 18]


In [7]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

2 * a + b

array([12, 24, 36])

### 2차원 배열
1. ndarray는 N - Dimensional Array의 약자 
2. 2차원 배열은 행렬(Matrix)


In [8]:
c = np.array([[0, 1, 2], [3, 4, 5]])
c
# 2차원 배열 

array([[0, 1, 2],
       [3, 4, 5]])

In [9]:
print('행의 갯수 : ', len(c)) 
print('열의 갯수 : ', len(c[0]))

행의 갯수 :  2
열의 갯수 :  3


### 3차원 배열 

In [16]:
d = np.array([[[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]],
              [[11, 12, 13, 14],
              [15, 16, 17, 18],
              [19, 20, 21, 22]]])

In [17]:
d
# 3차원 

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[11, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22]]])

In [19]:
print('Array 깊이 : ',len(d))
print('행의 갯수 : ', len(d[0]))
print('열의 갯수 : ', len(d[0][0]))
# 3차원은 앞에 array 깊이가 나오고 행, 열 순으로 나온다 

Array 깊이 :  2
행의 갯수 :  3
열의 갯수 :  4


### 배열의 차원과 크기 알아내기 

In [21]:
print('배열의 차원 수 : ',a.ndim)
print('배열의 형태 : ',a.shape)

배열의 차원 수 :  1
배열의 형태 :  (3,)


In [22]:
print('배열의 차원 수 : ',c.ndim)
print('배열의 형태 : ',c.shape)

배열의 차원 수 :  2
배열의 형태 :  (2, 3)


In [23]:
print('배열의 차원 수 : ',d.ndim)
print('배열의 형태 : ',d.shape)

배열의 차원 수 :  3
배열의 형태 :  (2, 3, 4)


### 배열의 인덱싱 

In [25]:
print(a)
print(a[1])
print(a[-1])

[1 2 3]
2
3


In [27]:
print(c)
print('첫번째 행 첫번째 열 : ', c[0, 0])
print('첫번째 행 두번째 열 : ', c[0, 1])

[[0 1 2]
 [3 4 5]]
첫번째 행 첫번째 열 :  0
첫번째 행 두번째 열 :  1


### 배열의 슬라이싱 

In [32]:
print(c)
print('첫번째 행 전체 : ', c[0,:])
print('두번째 열 전체 : ', c[:,1])
print(c[:2,:2])

[[0 1 2]
 [3 4 5]]
첫번째 행 전체 :  [0 1 2]
두번째 열 전체 :  [1 4]
[[0 1]
 [3 4]]


In [33]:
m = np.array([[0, 1, 2, 3, 4],
              [5, 6, 7, 8, 9],
              [10, 11, 12, 13, 14]])

In [42]:
print('7을 인덱싱 : ', m[1:2, 2:3])
print('1를 인덱싱 : ', m[2:3, 4:5])
print('[6,7]을 인덱싱 : ', m[1:2, 1:3])
print('[7,12]를 인덱싱 : ', m[1:3, 2:3])
print('[[3,4], [8,9]]를 인덱싱 : ', m[0:2, 3:5])

7을 인덱싱 :  [[7]]
1를 인덱싱 :  [[14]]
[6,7]을 인덱싱 :  [[6 7]]
[7,12]를 인덱싱 :  [[ 7]
 [12]]
[[3,4], [8,9]]를 인덱싱 :  [[3 4]
 [8 9]]


In [44]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
idx = np.array([True, False, True, False, True,
                False, True, False, True, False])
a[idx]
# 짝수인 원소만 골라내는 방법 

array([0, 2, 4, 6, 8])

In [47]:
print(a % 2)
print(a % 2 == 0 )
# 짝수인지 아닌지 판별 

[0 1 0 1 0 1 0 1 0 1]
[ True False  True False  True False  True False  True False]


In [48]:
a[a % 2 == 0]
# ==이 True, False로 나온다는 것을 활용해 인덱스를 바탕으로 array 값을 도출 

array([0, 2, 4, 6, 8])

In [50]:
a = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
idx = np.array([0, 2, 4, 6, 8])
a[idx]
# 인덱스는 위치만 알려줌으로 이렇게 해서 array에서 홀수만 추출 가능 

array([11, 33, 55, 77, 99])

### 다차원 배열 인덱싱 

In [52]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [53]:
a[:, [True, False, False, True]]
# 1, 4열만 인덱싱 

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [54]:
a[[2, 0, 1],:]
# 배열의 행의 순서를 조정 가능 

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [55]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
              11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [75]:
idx = [2, 5, 8, 11, 14, 17]
print('3의 배수 : ', x[idx])
print('3의 배수 : ', x[x % 3 == 0])
print('4로 나누면 1이 남는 수 : ', x[x % 4 == 1])
print('3으로 나누면 나누어지고 4로 나누면 1이 남는 수 : ', x[(x % 3 == 0) & (x % 4 == 1)])


3의 배수 :  [ 3  6  9 12 15 18]
3의 배수 :  [ 3  6  9 12 15 18]
4로 나누면 1이 남는 수 :  [ 1  5  9 13 17]
3으로 나누면 나누어지고 4로 나누면 1이 남는 수 :  [9]
